# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# # split panes using | and -
# bind | split-window -h
# bind - split-window -v
# unbind '"'
# unbind %

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf
# vim navigatoin
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on
# start windows numbering at 1
set -g base-index 1

# DESIGN TWEAKS
# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
# clock mode
setw -g clock-mode-colour "#fabd2f"
# copy mode
setw -g mode-style 'fg=#282828 bg=#fabd2f bold'
# panes
set -g pane-border-style 'fg=#3c3836'
set -g pane-active-border-style 'fg=#458588'
# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=#282828 fg=#ebdbb2'
set -g status-left ''
set -g status-left-length 10
set -g status-right-style 'fg=#282828 bg=#fabd2f'
set -g status-right ' #S #{session_id} | %Y-%m-%d %H:%M '
set -g status-right-length 80
setw -g window-status-current-style 'fg=#282828 bg=#458588 bold'
setw -g window-status-current-format ' #I #W  '
setw -g window-status-style 'fg=#928374 bg=#282828'
setw -g window-status-format ' #I #[fg=#ebdbb2]#W #[fg=#928374]#F '
setw -g window-status-bell-style 'fg=#282828 bg=#fb4934 bold'

# messages
set -g message-style 'fg=#282828 bg=#fabd2f bold'
