---
omz_dir: "{{ ansible_env.HOME }}/.oh-my-zsh"
zsh_custom: "{{ ansible_env.HOME }}/.oh-my-zsh/custom"
zsh_plugins:
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions
  zsh-syntax-highlighting: https://github.com/zsh-users/zsh-syntax-highlighting
  zsh-completions: https://github.com/zsh-users/zsh-completions
