# Generated by `nixos-generate-config --show-hardware-config --no-filesystems`
# on p15v (Ubuntu), 2026-10-10. Filesystems come from disko.nix. Dropped:
# nixpkgs.hostPlatform (the flake sets nixpkgs.pkgs) and the dm-snapshot
# initrd module (it was there for Ubuntu's LVM; disko uses plain btrfs).
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "rtsx_pci_sdmmc"
  ];
  boot.kernelModules = [ "kvm-intel" ];

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
