---
# GitHub organization/username; inherited from stow role via github_user
dev_repos_org: "{{ github_user }}"
dev_repos_root: "{{ ansible_env.HOME }}/dev/{{ github_user.split('-')[0] }}"
dev_repos_list:
  - public
  - secrets
  - my-tools
  - zezav-terraform
  - zezav-bolt
