# ~/.config/foot/foot.ini
[main]
font=MesloLGS Nerd Font Mono:size=9, Noto Color Emoji:size=9, monospace
initial-color-theme=1
pad=8x8

[colors]
# Gruvbox PITCH BLACK - maximální kontrast
background=000000
foreground=fbf1c7
regular0=000000
regular1=fb4934
regular2=b8bb26
regular3=fabd2f
regular4=83a598
regular5=d3869b
regular6=8ec07c
regular7=ebdbb2
bright0=928374
bright1=fb4934
bright2=b8bb26
bright3=fabd2f
bright4=83a598
bright5=d3869b
bright6=8ec07c
bright7=ffffff

[colors2]
# Gruvbox Light PURE WHITE - bez žluté, maximální kontrast
background=ffffff
foreground=000000
regular0=ffffff
regular1=9d0006
regular2=79740e
regular3=b57614
regular4=076678
regular5=8f3f71
regular6=427b58
regular7=3c3836
bright0=7c6f64
bright1=cc241d
bright2=427b58
bright3=af8700
bright4=005f87
bright5=5f005f
bright6=005f5f
bright7=000000
