bindsym $mod+Print exec grim -g "$(slurp)" - | wl-copy
bindsym $mod+Shift+Print exec grim -g "$(slurp)" - | swappy -f -
# Move the current workspace to a different monitor (output) using Arrow Keys
bindsym $mod+Ctrl+Shift+Left move workspace to output left
bindsym $mod+Ctrl+Shift+Down move workspace to output down
bindsym $mod+Ctrl+Shift+Up move workspace to output up
bindsym $mod+Ctrl+Shift+Right move workspace to output right

# Move the current workspace to a different monitor (output) using Vim Keys
bindsym $mod+Ctrl+Shift+h move workspace to output left
bindsym $mod+Ctrl+Shift+j move workspace to output down
bindsym $mod+Ctrl+Shift+k move workspace to output up
bindsym $mod+Ctrl+Shift+l move workspace to output right
