bindsym --to-code $mod+Print exec grim -g "$(slurp)" - | wl-copy
bindsym --to-code $mod+Shift+Print exec grim -g "$(slurp)" - | swappy -f -
# Toggle screen recording (rofi asks for audio source, slurp for region)
bindsym --to-code $mod+Ctrl+Print exec ~/.local/bin/screenrecord
# Move the current workspace to a different monitor (output) using Arrow Keys
bindsym --to-code $mod+Ctrl+Shift+Left move workspace to output left
bindsym --to-code $mod+Ctrl+Shift+Down move workspace to output down
bindsym --to-code $mod+Ctrl+Shift+Up move workspace to output up
bindsym --to-code $mod+Ctrl+Shift+Right move workspace to output right

# Move the current workspace to a different monitor (output) using Vim Keys
bindsym --to-code $mod+Ctrl+Shift+h move workspace to output left
bindsym --to-code $mod+Ctrl+Shift+j move workspace to output down
bindsym --to-code $mod+Ctrl+Shift+k move workspace to output up
bindsym --to-code $mod+Ctrl+Shift+l move workspace to output right
