input "type:touchpad" {
  natural_scroll enabled
  tap enabled
}

input "type:keyboard" {
  xkb_layout "us,cz"
  xkb_variant ",qwerty"
  xkb_options "grp:alt_shift_toggle,grp:switch"
  xkb_numlock enabled
}
bindswitch lid:on exec swaylock  # Zamkne obrazovku při zavření
bindswitch lid:off exec swaymsg output eDP-1 enable # Zapne displej po otevření
