---
stow_repo: "https://github.com/zezav-cz/.dot.git"
stow_version: ubuntu
stow_dest: "{{ ansible_env.HOME }}/.dot"
stow_packages:
  - git
  - mise
  - nvim
  - rofi
  - ssh-agent
  - sway
  - systemd
  - tmux
  - zsh
  - foot
  - k9s
  - nwg-displays
stow_no_folding:
  - my-scripts
  - pgcli
  - vscode
lazy_nvim_repo: "https://github.com/folke/lazy.nvim.git"
lazy_nvim_path: "{{ ansible_env.HOME }}/.local/share/nvim/lazy/lazy.nvim"
